version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

networks:
  nginx-proxy:
    external: true

services:
  mqtt:
    build:
      context: .
      dockerfile: ./compose/production/mqtt/Dockerfile
    image: lakessensor_production_mqtt
    container_name: lakessensor_production_mqtt
    depends_on:
      - django
    volumes:
      - ./mqtt_listener:/app:z
    env_file:
      - ./.envs/.production/.mqtt
    command: /start

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: lakessensor_production_django
    container_name: lakessensor_production_django
    volumes:
      - production_django_media:/app/lakessensor/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    environment:
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${API_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - default
      - nginx-proxy

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lakessensor_production_postgres
    container_name: lakessensor_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: lakessensor_production_nginx
    container_name: lakessensor_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro

  frontend:
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
      args:
        - REACT_APP_BACKEND_API=https://${API_DOMAIN}/api
    image: lakessensor_production_frontend
    container_name: lakessensor_production_frontend
    depends_on:
      - django
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - default
      - nginx-proxy
