# Generated by Django 4.2.11 on 2024-05-25 00:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=35, unique=True)),
                ('mac', models.CharField(max_length=17)),
                ('model_name', models.CharField(max_length=25)),
                ('primary_lake', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('session', models.PositiveIntegerField()),
                ('read_date', models.DateTimeField(verbose_name='date read')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=4, max_digits=8)),
                ('water_temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('air_temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('air_humidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorpipeline.device')),
            ],
        ),
        migrations.CreateModel(
            name='AnalogReading',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rain_past24hrs', models.BooleanField(default=False)),
                ('reading_place', models.CharField(choices=[('IN', 'Dentro del lago'), ('SL', 'Orilla del lago')], default='SL', max_length=2)),
                ('forel_ule_scale', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)])),
                ('secchi_depth', models.PositiveSmallIntegerField()),
                ('digital_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorpipeline.reading')),
            ],
        ),
    ]
