# Generated by Django 4.2.11 on 2025-04-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0002_alter_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogreading',
            name='digital_reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensorpipeline.reading'),
        ),
    ]
