# Generated by Django 4.2.11 on 2025-04-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0003_alter_analogreading_digital_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogreading',
            name='digital_reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analog_reading', to='sensorpipeline.reading'),
        ),
    ]
