# Generated by Django 4.2.11 on 2026-02-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0004_alter_analogreading_digital_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='air_humidity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reading',
            name='air_temp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reading',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reading',
            name='water_temp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
