# Generated by Django 4.2.11 on 2026-03-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0005_alter_reading_air_humidity_alter_reading_air_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='session',
            new_name='device_session',
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorpipeline.device')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_readings', to='sensorpipeline.readingsession'),
            preserve_default=False,
        ),
    ]
