# Generated by Django 4.2.11 on 2026-03-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0006_rename_session_reading_device_session_readingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogreading',
            name='digital_reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analog_reading', to='sensorpipeline.readingsession'),
        ),
    ]
