# Generated by Django 4.2.11 on 2026-07-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0007_alter_analogreading_digital_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
