# Generated by Django 4.2.11 on 2026-07-15 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorpipeline', '0008_lake'),
    ]

    operations = [
        migrations.CreateModel(
            name='LakeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_date', models.DateField()),
                ('analysis_date', models.DateField()),
                ('laboratory', models.CharField(max_length=100)),
                ('analyst', models.CharField(max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lake_samples', to=settings.AUTH_USER_MODEL)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='sensorpipeline.lake')),
            ],
        ),
    ]
