# Generated by Django 4.2.11 on 2026-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0014_rename_primary_lake_lake_device_primary_lake'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='default_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
