# Generated by Django 4.2.11 on 2026-08-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0015_device_default_latitude_device_default_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
