# Generated by Django 4.2.11 on 2026-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorpipeline', '0016_readingsession_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakesample',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
